#!/usr/bin/env bash
# blindtube-web deploy script
# First run: prompts for .env, creates + installs systemd service, builds, starts.
# Subsequent runs (rebuild): rebuilds binary and restarts the service.
# Must be run from the go/ directory of the blindtube repo.
set -euo pipefail

BOLD="\033[1m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
RED="\033[1;31m"
CYAN="\033[1;36m"
RESET="\033[0m"

info()    { echo -e "${CYAN}==>${RESET} ${BOLD}$*${RESET}"; }
success() { echo -e "${GREEN} ✓${RESET}  $*"; }
warn()    { echo -e "${YELLOW} !${RESET}  $*"; }
die()     { echo -e "${RED}ERROR:${RESET} $*" >&2; exit 1; }
ask()     { echo -e -n "${BOLD}$1${RESET} "; }

# ── Sanity checks ────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "${SCRIPT_DIR}/go.mod" ]] || die "Run this script from the blindtube/go/ directory."

command -v go       >/dev/null 2>&1 || die "Go is not installed. Install from https://go.dev/dl/"
command -v sudo     >/dev/null 2>&1 || die "sudo is required."
command -v systemctl>/dev/null 2>&1 || die "systemd is required."

CURRENT_USER="$(whoami)"
CURRENT_GROUP="$(id -gn)"

BIN_PATH="${SCRIPT_DIR}/blindtube-web"
SERVICE_NAME="blindtube"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
ENV_FILE="${SCRIPT_DIR}/.env"
LOG_DIR="${SCRIPT_DIR}/logs"

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║     blindtube-web  deploy / rebuild      ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${RESET}"
echo ""

# ── Helper: find a free TCP port ─────────────────────────────────────────────

find_free_port() {
    local start="${1:-8080}"
    local port="$start"
    while ss -tlnH 2>/dev/null | awk '{print $4}' | grep -q ":${port}$"; do
        port=$((port + 1))
    done
    echo "$port"
}

# ── .env setup ───────────────────────────────────────────────────────────────

setup_env() {
    echo ""
    info ".env setup"
    echo ""

    if [[ -f "${ENV_FILE}" ]]; then
        warn ".env already exists at ${ENV_FILE}"
        ask "Reconfigure it? [y/N]:"
        read -r reconfigure
        [[ "${reconfigure,,}" == "y" ]] || { info "Keeping existing .env."; return; }
    fi

    # Suggest a free port as default
    local suggested_port
    suggested_port="$(find_free_port 8080)"
    if [[ "$suggested_port" != "8080" ]]; then
        warn "Port 8080 is in use. Suggested free port: ${suggested_port}"
    fi

    echo "── Server settings ──────────────────────────────────"
    ask "Listen address [${suggested_port}]:"
    read -r input_addr
    local addr=":${input_addr:-$suggested_port}"
    # If user typed a full address like :9000 keep it as-is
    [[ "${input_addr:-}" == :* ]] && addr="${input_addr}"

    echo ""
    echo "── Caddy / reverse proxy settings ──────────────────"
    echo "   blindtube-web will run on ${addr} and Caddy will"
    echo "   proxy tube.denizsincar.ru → 127.0.0.1${addr}"
    echo ""
    ask "Domain (for Caddy config hint) [tube.denizsincar.ru]:"
    read -r domain
    domain="${domain:-tube.denizsincar.ru}"

    cat > "${ENV_FILE}" << EOF
# blindtube-web environment — generated by deploy.sh
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Listen address for blindtube-web (-addr flag)
BLINDTUBE_ADDR=${addr}

# Domain shown in deploy output (used for Caddy config hint only)
BLINDTUBE_DOMAIN=${domain}
EOF
    chmod 600 "${ENV_FILE}"
    success ".env written to ${ENV_FILE} (mode 600)"
    echo ""
    echo -e "  Add to your Caddyfile:"
    echo -e "    ${BOLD}${domain} {${RESET}"
    echo -e "    ${BOLD}    reverse_proxy 127.0.0.1${addr}${RESET}"
    echo -e "    ${BOLD}}${RESET}"
    echo ""
}

# ── Source .env ───────────────────────────────────────────────────────────────

load_env() {
    if [[ -f "${ENV_FILE}" ]]; then
        # Export each non-comment, non-empty line
        set -o allexport
        # shellcheck disable=SC1090
        source "${ENV_FILE}"
        set +o allexport
    fi
    BLINDTUBE_ADDR="${BLINDTUBE_ADDR:-:8080}"
}

# ── Build ─────────────────────────────────────────────────────────────────────

build() {
    info "Building blindtube-web..."
    cd "${SCRIPT_DIR}"
    go mod tidy
    go build -o "${BIN_PATH}" ./cmd/blindtube-web
    success "Binary: ${BIN_PATH}"
}

# ── Systemd service ───────────────────────────────────────────────────────────

install_service() {
    info "Installing systemd service ${SERVICE_NAME}..."

    mkdir -p "${LOG_DIR}"

    sudo tee "${SERVICE_FILE}" > /dev/null << EOF
[Unit]
Description=BlindTube web backend (tube.denizsincar.ru)
Documentation=https://github.com/denizsincar29/blindtube
After=network.target

[Service]
Type=simple
User=${CURRENT_USER}
Group=${CURRENT_GROUP}
WorkingDirectory=${SCRIPT_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=${BIN_PATH} -addr \${BLINDTUBE_ADDR}
Restart=on-failure
RestartSec=5
StandardOutput=append:${LOG_DIR}/blindtube.log
StandardError=append:${LOG_DIR}/blindtube.error.log
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable "${SERVICE_NAME}"
    success "Service installed and enabled: ${SERVICE_FILE}"
}

service_exists() {
    local state
    state="$(systemctl show "${SERVICE_NAME}.service" -p LoadState --value 2>/dev/null || true)"
    [[ -n "$state" && "$state" != "not-found" ]]
}

service_running() {
    systemctl is-active --quiet "${SERVICE_NAME}" 2>/dev/null
}

restart_service() {
    if service_running; then
        info "Restarting ${SERVICE_NAME}..."
        sudo systemctl restart "${SERVICE_NAME}"
    else
        info "Starting ${SERVICE_NAME}..."
        sudo systemctl start "${SERVICE_NAME}"
    fi
    sleep 2
    if service_running; then
        success "${SERVICE_NAME} is running!"
    else
        warn "Service did not start. Check logs:"
        warn "  sudo journalctl -u ${SERVICE_NAME} -n 50"
        warn "  tail -f ${LOG_DIR}/blindtube.error.log"
    fi
}

# ── Main ──────────────────────────────────────────────────────────────────────

if service_exists; then
    # ── Rebuild mode ────────────────────────────────────────────────────────
    info "Service already installed — rebuild mode."
    build
    load_env
    restart_service

    echo ""
    echo -e "${GREEN}${BOLD}════════════════════════════════════════${RESET}"
    echo -e "${GREEN}${BOLD}  Rebuild complete!${RESET}"
    echo -e "${GREEN}${BOLD}════════════════════════════════════════${RESET}"
    echo ""
    echo -e "  ${BOLD}sudo systemctl status ${SERVICE_NAME}${RESET}"
    echo -e "  ${BOLD}sudo journalctl -u ${SERVICE_NAME} -f${RESET}"
    echo -e "  ${BOLD}tail -f ${LOG_DIR}/blindtube.log${RESET}"
    echo ""
else
    # ── First-time install mode ──────────────────────────────────────────────
    setup_env
    load_env
    build
    install_service
    restart_service

    echo ""
    echo -e "${GREEN}${BOLD}════════════════════════════════════════${RESET}"
    echo -e "${GREEN}${BOLD}  Deploy complete!${RESET}"
    echo -e "${GREEN}${BOLD}════════════════════════════════════════${RESET}"
    echo ""
    echo -e "  Listening on:  ${BOLD}${BLINDTUBE_ADDR}${RESET}"
    echo -e "  Domain hint:   ${BOLD}${BLINDTUBE_DOMAIN:-tube.denizsincar.ru}${RESET}"
    echo ""
    echo -e "  Service commands:"
    echo -e "    ${BOLD}sudo systemctl status ${SERVICE_NAME}${RESET}       — status"
    echo -e "    ${BOLD}sudo journalctl -u ${SERVICE_NAME} -f${RESET}       — live logs"
    echo -e "    ${BOLD}sudo systemctl restart ${SERVICE_NAME}${RESET}      — restart"
    echo -e "    ${BOLD}sudo systemctl stop ${SERVICE_NAME}${RESET}         — stop"
    echo ""
    echo -e "  To rebuild after git pull:"
    echo -e "    ${BOLD}./deploy.sh${RESET}"
    echo ""
fi
